### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by amanbadhwar** [r03ert0/brainspell#12]
Hi Roberto,

Could you add a feature to download tables added?
Also, is it possible to completely remove empty tables? It makes for cleaner look per article.

Thanks in advance.

Best,
Aman

**Comment by r03ert0** [comment]
Hi Aman,

would you like to download them in csv (just data, one table per file), or an html file with data + text?

**Comment by amanbadhwar** [comment]
Hi Roberto,

I would like to download them in csv. The underlying issue is that in order to conduct a meta-analyses, quite a few of the tables need to be reorganized, since they mix different groups in the same table. I was going to do this locally, but eventually we would need this on brainspell (maybe a local version).
Another option might be to add user defined tables to brainspell. Howeever, you might have more creative ideas.

Best,
Aman

**Comment by r03ert0** [comment]
and would it be enough to add the possibility of splitting tables? or more complex reorganisations are also required?

**Comment by amanbadhwar** [comment]
Hi Roberto,

From what I have encountered so far, splitting the tables would work. I am hoping this remains true for the remaining articles.

Best,
Aman

**Comment by r03ert0** [comment]
I updated the article pages so that empty tables are not displayed

**Comment by r03ert0** [comment]
I added a [Download] link to each article. When clicked it will download the title, reference, and abstract of the article, followed by all the tables with tab separated x, y, z coordinates.

**Comment by amanbadhwar** [comment]
Thanks Roberto! I tested it and it works.


Best,

Aman

________________________________
