### ISSUE TITLE
Symbols not retained in verbose table title

### ISSUE THREAD

**Issue by amanbadhwar** [r03ert0/brainspell#16]
Dear Roberto,
Would be helpful if the below described issue can be fixed.

eg. from http://brainspell.org/article/25679386
Table 3
Regions showing functional connectivity differences in the left and right thalamus among the late stage MCI early stage MCI and healthy control (P less than 0001 40 voxels corrected for multiple comparisons)
brainspell does the following:
(1) sign is dropped when < > = , . % & {} ! @ # $ ^ * - _ + " ? ' : ; ~ / \ | ` Currently I am using words instead of sign, but this is not always clear either as shown above.
(2) Problem present on Firefox, Chrome, and Safari
(3) No problems with ( ) and [ ]

Best,
Aman

**Comment by r03ert0** [comment]
fixed!
