### ISSUE TITLE
Title and Caption dissapear on me

### ISSUE THREAD

**Issue by dnkennedy** [r03ert0/brainspell#17]
I've been adding Titles and Captions to the tables of http://brainspell.org/article/17321151

I fill them in, leave the page, and return to the page, and they've all disappeared.

**Comment by amanbadhwar** [comment]
Hi David,

Which browser are you using? Are you hitting enter after adding titles and captions?

Best,
Aman

**Comment by dnkennedy** [comment]
usually use Firefox, no, probably not hitting enter, will try that.

Dk

Sent from my Verizon Wireless 4G LTE DROID
On Sep 18, 2015 10:22 AM, AmanPreet Badhwar <notifications@github.com> wrote:

Hi David,

Which browser are you using? Are you hitting enter after adding titles and captions?

Best,
Aman

**Comment by dnkennedy** [comment]
hitting 'return' is the key! That make it work.

DK

----
David N. Kennedy, Ph.D.
Department of Psychiatry
Division of Neuroinformatics
University of Massachusetts Medical Center
David.Kennedy@umassmed.edu
________________________________

**Comment by amanbadhwar** [comment]
Great!
Aman

**Comment by r03ert0** [comment]
I'll try to add some feedback to the interface to let people know when a field has been edited...

**Comment by r03ert0** [comment]
1. title and caption fields occupy now 100% of the width no matter the length of the text inside, preventing them from disappear
2. when a text field becomes editable, it turns light grey, when they are saved, they lose the light grey background
3. storage of the fields is now triggered by an enter, a tab (which makes focus jump to the next editable field), or by clicking somewhere else (anything that moves the focus out of the field)
4. title and caption fields appear outlined when edition is allowed (i.e., user logged in)

i'll close the issue, but let me know if it the changes work for you

cheers,
roberto
