### ISSUE TITLE
Split table should inherit properties

### ISSUE THREAD

**Issue by dnkennedy** [r03ert0/brainspell#18]
When splitting a table, it might be good to inherit the cognitive/brainmap tags and table title and caption, by default, perhaps.

**Comment by amanbadhwar** [comment]
Hi David, we are working on a nomenclature for that currently. Will you be splitting a lot of tables in the next few days?

**Comment by dnkennedy** [comment]
No, I won't be doing lots, just working up a test case.

Dk

Sent from my Verizon Wireless 4G LTE DROID
On Sep 18, 2015 10:20 AM, AmanPreet Badhwar <notifications@github.com> wrote:

Hi David, we are working on a nomenclature for that currently. Will you be splitting a lot of tables in the next few days?

**Comment by r03ert0** [comment]
Done. Tables inherit tags, titles and captions after a split.
