### ISSUE TITLE
add new tables to existing article

### ISSUE THREAD

**Issue by angela-tam** [r03ert0/brainspell#24]
Hi Roberto, I don't know what happened to this article (http://brainspell.org/article/25080229) but when I wanted to see its tables, there was nothing and there doesn't seem to be an option to add new tables to an article that has already been created.

**Comment by r03ert0** [comment]
Hi Angela,

I deleted it from the DB. You can add it again now and it'll let you add
the tables.

best,
roberto

**Comment by r03ert0** [comment]
I'll close this issue. Let me know if it has to be opened again.
