### ISSUE TITLE
Split and Import issues 

### ISSUE THREAD

**Issue by amanbadhwar** [r03ert0/brainspell#26]
Dear Roberto,
Both the *split* and *import* buttons are not working as previously tested. I have managed to make an entire table (Table S3) disappear trying to make the buttons work. Now I don't have a way of adding the table back in for the article specified (http://brainspell.org/article/25511078).
Please find below an attachment (txt) of what it used to look like before my manipulations.
[25511078.txt](https://github.com/r03ert0/brainspell/files/40220/25511078.txt)
Best,
Aman

**Comment by r03ert0** [comment]
Hi Aman,
I fixed a bug in brainspell that arrived when splitting an experiment without tags.
To bring back Table S3 I added an empty row to Table S1, splitted it to create a new empty table, and added the coordinates back (using the import function and pasting from your text file).
I'll close the issue.
