### ISSUE TITLE
Split tables dissapearing

### ISSUE THREAD

**Issue by amanbadhwar** [r03ert0/brainspell#27]
Dear Roberto,

So for the following article (http://brainspell.org/article/24996404) I was able to split the original megatable table into 13 smaller tables. I need to perform some more splitting, but any additional split tables are not being retained by brainspell. Is there a brainspell limit on the number of tables per article?

Best,
Aman

**Comment by r03ert0** [comment]
Hi Aman,
I found where the bug comes from. It's not related to the tables but to the 3D brain renders. Each 3D brain creates its own three.js renderer, and after a few renderers have been created (about 10) it's not possible to create any more. The solution is to have a single renderer instead of separate ones, and crop the display to make them appear as separate (using three.js 'scissors'). I'll try to work on it asap.
cheers,
roberto

**Comment by amanbadhwar** [comment]
Thanks Roberto!

**Comment by r03ert0** [comment]
should be fixed now.
could you give it a try?
I'll close the issue.

**Comment by amanbadhwar** [comment]
Dear Roberto,
So I checked the split button 'fix' on http://brainspell.org/article/24996404. Unfortunately, my newly split tables (after Table S3_brainspellM) are still being lost upon referesh. I have tried with both chrome and firefox. I have the most updated version of chrome. Let me try with a different paper.

**Comment by r03ert0** [comment]
hmm... strange. I get them here.

At which level you split the table?

i'll try to do it



On Mon, Dec 14, 2015 at 3:59 PM, AmanPreet Badhwar <notifications@github.com

**Comment by r03ert0** [comment]
I see 2 tables called Table S3_brainspellM, one with 1 location, the next
one with ~73 locations.
Is that correct?

**Comment by amanbadhwar** [comment]
I did a split at Table S3_brainspellM, 7th row, after coordinates -26,-72, -32. I was trying to save the last table with a new name, and that is not being refreshed either (You are right with the 2 tables with the same name).


I'll try with a reboot of my system maybe.


Best,

Aman


________________________________

**Comment by amanbadhwar** [comment]
Dear Roberto,


So I have tried it out on 3 different computers now. When the number of split tables is >10, it does not want to save any updates (upon refresh), be it chance in title or another split.

I am not experiencing these problems when there are a fewer number of tables.

Hope this helps (but from our end it does not seem like the issue has been resolved).

Best,

Aman


________________________________

**Comment by r03ert0** [comment]
now it's fixed! promise!

On Mon, Dec 14, 2015 at 7:03 PM, AmanPreet Badhwar <notifications@github.com
> wrote:

> Dear Roberto,
>
>
> So I have tried it out on 3 different computers now. When the number of
> split tables is >10, it does not want to save any updates (upon refresh),
> be it chance in title or another split.
>
> I am not experiencing these problems when there are a fewer number of
> tables.
>
> Hope this helps (but from our end it does not seem like the issue has been
> resolved).
>
> Best,
>
> Aman
>
>
> ________________________________
> From: Roberto Toro <notifications@github.com>
> Sent: Monday, December 14, 2015 11:16 AM
> To: r03ert0/brainspell
> Cc: Amanpreet Badhwar
> Subject: Re: [brainspell] Split tables dissapearing (#27)
>
> I see 2 tables called Table S3_brainspellM, one with 1 location, the next
> one with ~73 locations.
> Is that correct?
>
