### ISSUE TITLE
JSON has quotes in it!

### ISSUE THREAD

**Issue by vsoch** [r03ert0/brainspell#6]
Some silly author decided to have quotes in his abstract, and it's introducing an error into reading the json!  For example [this guy](http://brainspell.org/json/pmid/19289173) on line 4 (the abstract) gets all quotey:

`"active" voxels`

and so doing something like:

     import json
     import urllib2
     url = 'http://brainspell.org/json/pmid/19289173'
     text = urllib2.urlopen(url).read()
     myjson = json.loads(text)

results in an error! I tested escaping the quote, like this:

`\"active\" voxels`

and it works.  Would it be possible to escape the quotes in the abstract text? I can do a workaround for the time being, because it's a rather small thing.

**Comment by r03ert0** [comment]
fixed!
