### ISSUE TITLE
new articles are not saving

### ISSUE THREAD

**Issue by angela-tam** [r03ert0/brainspell#7]
After creating a new article and filling in the stereotaxic tables, the information does not appear to save properly.  The new article's title and abstract will show up at brainspell.org/article/PMID, however, the MeSH descriptors and stereotaxic tables are gone and there does not appear to be a way to re-add them.  Examples: http://brainspell.org/article/21769962 ; http://brainspell.org/article/20656843

**Comment by r03ert0** [comment]
The first one (21769962) had a no data at all. I just deleted it from the
DB. Try entering it again?
The second one had a character that was incorrectly parsed and prevented
the record from being read. If fixed and now the article is back.

can you send me a list of the other articles?

I'm leaving for the airport in a couple of few hours, but will try to check
that from the airport.

best,
roberto

**Comment by angela-tam** [comment]
Hi Roberto,

I entered 21769962 again and it was working okay for a bit, but then suddenly all the data just disappeared.  :(  But the tables for other new articles seem to be saving okay.

Thanks,
Angela

**Comment by r03ert0** [comment]
Hi Angela,

I looked into the DB entry for OMID 21769962. The entry should look like

<![CDATA[[{"title":"Significant Differences in HFC Network Connectivity
Between the Mild AD Group at Baseline and the CN
Group","caption":"","locations":["-33,-73,8","-24,-55,-10","-4,-67,10","-6,-69,5","6,-75,2","-4,-67,9","14,-81,27","-7,-65,58","5,-52,52","10,-39,63","27,39,36","41,23,11","11,24,36"]},{"title":"Significant
Differences in HFC Network Connectivity in the Mild AD Group Before and
After Donepezil
Treatment","caption":"","locations":["-31,-15,30","-22,-28,-2","2,-41,33","-33,8,-5","-11,-21,-21","-31,-20,-2","-10,-27,-3","-50,2,43","-45,-53,26","-47,-51,12","39,-5,46"]},{"title":"Cognitive
Neural Correlates Between Changes in Connectivity Strength in the HFC
Network With MMSE and ADAScog Scores in Mild AD After
Donepezil","caption":"","locations":["-27,-13,-28","-49,11,26","-47,-2,26","-37,-1,5","-46,6,37","-38,39,30","-13,10,50"]}]]]>

but instead, it has a lot of tabs, and a special character at the end of
the 2nd table title (see below). I think (but not yet verified; however,
removing them makes the record readable again) that these characters
prevent the parsing of the record. The long term solution is to filter
special characters on user entry. Those are not characters that you
entered, yes?



<![CDATA[[{"title":"Significant Differences in HFC Network Connectivity
Between the Mild AD Group at Baseline and the CN
Group","caption":"","locations":["-33,-73,8","-24,-55,-10","-4,-67,10","-6,-69,5","6,-75,2","-4,-67,9","14,-81,27","-7,-65,58","5,-52,52","10,-39,63","27,39,36","41,23,11","11,24,36"]},{"title":"






                    Significant Differences in HFC Network Connectivity in
the Mild AD Group Before and After Donepezil TreatmentÂ



","caption":"","locations":["-31,-15,30","-22,-28,-2","2,-41,33","-33,8,-5","-11,-21,-21","-31,-20,-2","-10,-27,-3","-50,2,43","-45,-53,26","-47,-51,12","39,-5,46"]},{"title":"






                    Cognitive Neural Correlates Between Changes in
Connectivity Strength in the HFC Network With MMSE and ADAScog Scores in
Mild AD After DonepezilÂ



","caption":"","locations":["-27,-13,-28","-49,11,26","-47,-2,26","-37,-1,5","-46,6,37","-38,39,30","-13,10,50"]}]]]>

**Comment by angela-tam** [comment]
Hi Roberto,

That's really strange because I didn't type in that special character... Although I was copying and pasting the titles from the article's pdf, so maybe something weird happened there?

Best,
Angela

**Comment by r03ert0** [comment]
that's it maybe! so probably the tabs come from the copy paste as well?
(I'll find an input validator script or something)

**Comment by angela-tam** [comment]
yeah the tabs probably come from the copy paste too.  I'll type in new titles for now :)

**Comment by r03ert0** [comment]
I added a filter, like this:
    var	value=$(obj).text(); // the value entered by the user
    var value2=value.replace(/[^a-zA-Z0-9\(\)\[\]]/g, ""); // Filter out value
    $(obj).text(value2); // the filtered value is put back into the field to provide feedback
Could you check that it works?

**Comment by angela-tam** [comment]
Okay so I tried with this new article I just created: http://brainspell.org/article/25679386
And it looks like it doesn't save my titles... whether I copy paste or type it in.

**Comment by r03ert0** [comment]
'space' was not among the ok characters... now it's added. Let me know if there's any other bug. I'll close the issue for the moment.
